[environments.production.build]
POETRY_VIRTUALENVS_CREATE=false

[build]
builder = "NIXPACKS"
builderCommand = "pip -m install poetry && poetry install"

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
